version: '3'
services:

  #NODE Service
  app:
    image: node:${NODE_V}
    container_name: app_${DOCKER_NAME}
    restart: unless-stopped
    entrypoint: sh /init.sh
    tty: true
    working_dir: /app
    volumes:
      - ${PROJECT_PATH}:/app
      - ./init.sh:/init.sh
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${SOCKET_PORT}:${SOCKET_PORT}
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge